dcos/Makefile
dcos/tests/test_spark.py

- Changed SPARK_DIR to point to enclosing directory. No longer need to clone a separate repo.
- By default, we always build a Spark distribution from source, rather than downloading the one in the manifest file.
- Temporarily disabled secrets test.

[SPARK-574] For CI setup: changed SPARK_DIR to point to enclosing directory

---

resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterSchedulerSource.scala

Adds multiple of the following metric types to the dispatcher: 
- Counters: The total number of times that submissions have entered states
- Timers: The duration from submit or launch until a submission entered a given state
- Histogram: The retry counts at time of retry
Unlike the existing metrics which are polling-based, these are pushed from the dispatcher scheduler code.
Did a fresh build and performed a couple runs of SparkPi. The new metrics are being emitted and the numbers produced (from two successful runs) appear to make sense.

SPARK-723 Add many more metrics to dispatcher

---

core/src/main/scala/org/apache/spark/metrics/MetricsConfig.scala
core/src/main/scala/org/apache/spark/metrics/MetricsSystem.scala
dev/make-distribution.sh
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerSource.scala

Implements metrics in the coarse-grained driver implementation. The deprecated fine-grained driver is left as-is. Metrics include e.g. frequency of RPCs to/from Mesos, the internal state tracking of tasks/agents, and durations for bringing up the tasks.
Checked it by hand in a few deployments, and the numbers appear to all add up with nothing missing.

SPARK-740 Driver metrics

---

core/src/main/scala/org/apache/spark/deploy/DCOSSecretStoreUtils.scala
core/src/main/scala/org/apache/spark/deploy/SparkHadoopUtil.scala
core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala
core/src/main/scala/org/apache/spark/deploy/rest/RestSubmissionClient.scala
core/src/main/scala/org/apache/spark/rdd/HadoopRDD.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosHadoopDelegationTokenManager.scala

Fixes the --proxy-user issue.
@susanxhuynh I added the fix so we can discuss the cli implementation options and agree on something.
One basic option is move the secrets code in this PR to dcos Spark cli but that would require 
the cli to download the spark distro, run spark submit code to generate the DTs (without the rest submission part) and then upload them as secrets to secret store. 
I remember that in the past cli used to download the distro. 
Design is attached: [design.pdf](https://github.com/mesosphere/spark/files/1989687/design.pdf)
Note: this can be merged directly here but it will bring dependencies in and will work only with spark-submit in cluster mode.
This patch also fixes:
a) the issue with the requirement of the keytab to exist locally at the spark submit side in cluster …

Support --proxy-user in cluster mode on DC/OS

---

core/src/main/scala/org/apache/spark/scheduler/cluster/CoarseGrainedClusterMessage.scala
core/src/main/scala/org/apache/spark/scheduler/cluster/CoarseGrainedSchedulerBackend.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala
resource-managers/mesos/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackendSuite.scala
resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/YarnAllocator.scala
resource-managers/yarn/src/main/scala/org/apache/spark/scheduler/cluster/YarnSchedulerBackend.scala

Using incremental integers as Executor IDs leads to a situation when Spark Executors launched by different Drivers have same IDs. When running on DCOS that means that Mesos Task IDs for Spark Executors can have duplicates too. This change introduces unique identifiers for both `CoarseGrainedSchedulerBackend` and `YarnAllocator` which are prepended to numeric ID thus allowing to distinguish Executors belonging to different drivers.
This PR reverts commit [ebe3c7f](https://github.com/apache/spark/commit/ebe3c7f290929588c822137b8bf27b18fe75393f): "initialize executorIdCounter after ApplicationMaster killed for max n…)" realted to Jira Issue [SPARK-12864](https://issues.apache.org/jira/browse/SPARK-12864) because it addressed the similar but YARN-case specific issue.
The change is verified by …

[DCOS-39150][SPARK] Support unique Executor IDs in cluster managers

---

core/src/main/scala/org/apache/spark/SecurityManager.scala
core/src/main/scala/org/apache/spark/executor/CoarseGrainedExecutorBackend.scala
core/src/main/scala/org/apache/spark/metrics/MetricsConfig.scala
core/src/main/scala/org/apache/spark/metrics/MetricsSystem.scala
core/src/main/scala/org/apache/spark/scheduler/cluster/CoarseGrainedClusterMessage.scala
core/src/main/scala/org/apache/spark/scheduler/cluster/CoarseGrainedSchedulerBackend.scala
docs/running-on-mesos.md
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterSchedulerSource.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerSource.scala
resource-managers/mesos/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterSchedulerSuite.scala
resource-managers/mesos/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackendSuite.scala
resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/YarnAllocator.scala
resource-managers/yarn/src/main/scala/org/apache/spark/scheduler/cluster/YarnSchedulerBackend.scala

This PR contains cherry-picked commits from 2.2 which weren't present in the upstream:
- Support for DSCOS_SERVICE_ACCOUNT_CREDENTIAL environment variable in MesosClusterScheduler (temporary workaround, should be removed when moving Spark to dcos-commons SDK)
- File Based Secrets support
- [SPARK-723][SPARK-740] Add Metrics to Dispatcher and Driver (number of metrics-related commits squashed into one)
- [SPARK-23941][MESOS] Mesos task failed on specific spark app name (defensive `shellEscape` for app name and config options)
- [DCOS-39150][SPARK] Support unique Executor IDs in cluster managers (switch from integer counters to `UUID` + index for executor ids)
This patch should pass all the tests in spark-build integration suite.

[DCOS-43430] rebase spark to 2.3 and cherry pick from 2.2

---

core/pom.xml
core/src/main/scala/org/apache/spark/rdd/RDDOperationScope.scala
core/src/main/scala/org/apache/spark/status/api/v1/JacksonMessageWriter.scala
core/src/test/scala/org/apache/spark/JsonTestUtils.scala
core/src/test/scala/org/apache/spark/deploy/history/HistoryServerSuite.scala
core/src/test/scala/org/apache/spark/ui/UISeleniumSuite.scala
pom.xml
sql/catalyst/pom.xml

Spark 3rd-party libraries have a number of CVEs and need to be upgraded in order to get newer versions with fixes.
List of upgrades for 3rd-party libraries having CVEs:
- CVE-2017-7658. jetty 9.3.11.v20160721 -> 9.3.24.v20180605
- CVE-2017-15095, CVE-2017-17485, CVE-2017-7525, CVE-2018-7489, CVE-2016-3720. jackson 2.6.5 -> 2.9.6.
- ZooKeeper 3.4.6 -> 3.4.13 (https://zookeeper.apache.org/doc/r3.4.13/releasenotes.html)
Integration tests from [mesosphere/spark-build](https://github.com/mesosphere/spark-build) repo

Upgrade of Jetty, Jackson, and ZooKeeper client versions

---

pom.xml

Resolves [DCOS-45197](https://jira.mesosphere.com/browse/DCOS-45197)
- upgrade of Hadoop dependencies from 2.7.3 to 2.7.4 for Spark Hadoop 2.7 profile
- fixes
- CVE-2016-6811
- CVE-2017-3166
- CVE-2017-3162 (is available since 2.7.0, see release notes)
Integration tests from [mesosphere/spark-build](https://github.com/mesosphere/spark-build)
- Hadoop dependencies upgraded for 2.7 build profile from 2.7.3 to 2.7.4 in order to fix `org.apache.hadoop_hadoop-hdfs:2.6.5` vulnerabilities: CVE-2016-6811, CVE-2017-3162, CVE-2017-3166. `org.apache.hadoop_hadoop-hdfs:2.6.5` is the last version in 2.6 line and doesn't contain fixes for given CVEs. It is recommended to use Spark with Hadoop 2.7 to avoid these vulnerabilities.

Upgrade of Hadoop dependencies for 2.7 profile from 2.7.3 to 2.7.4

---

pom.xml

Resolves [DCOS-45549](https://jira.mesosphere.com/browse/DCOS-45549) 
This PR bumps Hadoop profile from `2.7.4` -> `2.7.7` to fix `CVE-2018-8009`
As a benchmark, ran `mvn test` on `custom-branch-2.2.1-X` which has `hadoop-2.7.4`. That resulted in 4 failures in `Spark Project SQL`.
Re-reran `mvn test` on this branch with updated `hadoop-2.7.7` build and same 4 tests failed. 
The tests themselves need fixing but it doesn't appear bumping Hadoop fails any new tests or breaks dependencies.
- Fixes CVE-2018-8009

[DCOS-45549] Upgrade hadoop 2.7.4 -> 2.7.7

---

core/src/main/scala/org/apache/spark/executor/CoarseGrainedExecutorBackend.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosSchedulerBackendUtil.scala
resource-managers/mesos/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackendSuite.scala
resource-managers/mesos/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosSchedulerBackendUtilSuite.scala

* Previously, executors were instructed to bind to `0.0.0.0` address in case virtual network was specified via `spark.mesos.network.name` which made this address advertised to other executors and led to failures during shuffle jobs. Now responsibility to discover bind address is moved to the executor in case the virtual network is enabled thus allowing to bind to an address within this network
* Docker containerizer is fixed in order to allow running in virtual/overlay network by providing additional properties to `DockerInfo` builder
* unit tests added to validate the changes proposed in this PR
* integration tests for both Docker and Mesos containerizers from [mesosphere/spark-build](https://github.com/mesosphere/spark-build)

[DCOS-45840] CNI support for shuffle jobs

---

resource-managers/mesos/src/main/scala/org/apache/spark/deploy/rest/mesos/MesosRestServer.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
resource-managers/mesos/src/test/scala/org/apache/spark/deploy/rest/mesos/MesosSubmitRequestServletSuite.scala

This PR move Dispatcher default properties processing logic to an earlier phase when `MesosDriverDecription` is being constructed. This change is needed for applying default properties (`spark.mesos.network.*` in this case) not only to Spark Executors `ContainerInfo` but to Spark Driver itself when it is launched on Mesos.
* unit tests added to validate the changes proposed in this PR
* integration tests for both Docker and Mesos containerizers from [mesosphere/spark-build](https://github.com/mesosphere/spark-build/), https://github.com/mesosphere/spark-build/pull/472

[DCOS-46369] Spark Dispatcher should run Spark Drivers and Executors in the same virtual network if specified

---

core/src/main/scala/org/apache/spark/SecurityManager.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala
resource-managers/mesos/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterSchedulerSuite.scala

Resolves [DCOS-46585](https://jira.mesosphere.com/browse/DCOS-46585) && [COPS-4325](https://jira.mesosphere.com/browse/COPS-4325)
Customers experienced `--supervised` Spark jobs were retried multiple times in scenarios where an agent would crash, come back, and re-register even when those jobs had already relaunched on a different agent. That is:
```
- supervised driver is running on agent1
- agent1 crashes
- driver is relaunched on another agent as `<task-id>-retry-1`
- agent1 comes back online and re-registers with scheduler
- spark relaunches the same job as `<task-id>-retry-2`
- now there are two jobs running simultaneously
```
This is because when an agent would come back and re-register it would send a status update `TASK_FAILED` for its old driver-task. Previous logic would …

[DCOS-46585] Fix supervised driver retries on outdated tasks

---

resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala

`SPARK_USER` and `Utils.getCurrentUser` were ignored in `MesosClusterScheduler` when a Driver `TaskInfo` was constructed. This PR adds a user in `CommandInfo` for Spark Driver launched on Mesos.
* integration tests added in [mesosphere/spark-build](https://github.com/mesosphere/spark-build) https://github.com/mesosphere/spark-build/pull/492

[DCOS-49020]  Specify user in CommandInfo for Spark Driver launched on Mesos

---

docs/running-on-mesos.md
resource-managers/mesos/src/main/scala/org/apache/spark/deploy/mesos/config.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosFineGrainedSchedulerBackend.scala
resource-managers/mesos/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackendSuite.scala

* added boolean configuration property `spark.mesos.checkpoint`
* `spark.mesos.checkpoint` is used when drivers are submitted to Dispatcher
* unit test verifying that `spark.mesos.checkpoint` is respected
* Integration tests from [mesosphere/spark-build](https://github.com/mesosphere/spark-build)
* Added Mesos checkpointing support for Spark Drivers submitted to Dispatcher

[DCOS-40974] Mesos checkpointing support for Spark Drivers

---

resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosSchedulerUtils.scala

* Bugfix for Spark Executor ID being different from Mesos Task ID
* Bugfix: thread-safe sequential task IDs for Executors
* unit tests from this repo
* Integration tests from [mesosphere/spark-build](https://github.com/mesosphere/spark-build)
* [Bugfix] Fixed bug for Spark Executor ID being different from Mesos Task ID

[DCOS-51158] Improved Task ID assignment for Executor tasks

---

repl/src/test/scala/org/apache/spark/repl/ReplSuite.scala

* removed not working test which started failing when `MESOS_NATIVE_JAVA_LIBRARY` environment variable is set. Justification:
* current cluster url `localquiet` will never pass a regexp check when SparkContext is created 
* if change cluster url to `local` then there's no point in checking for Mesos integration specifically 
* the presence of `MESOS_NATIVE_JAVA_LIBRARY` environment variable doesn't mean that Mesos is available while Mesos native lib is used for building Mesos Cluster Scheduler
* this is an integration test which assumes Mesos cluster availability and doesn't play well with the rest of the tests (there's no YARN or K8s tests)
* unit tests from the current repo with `MESOS_NATIVE_JAVA_LIBRARY` environment variable enabled and disabled

[DCOS-51454] Remove irrelevant Mesos REPL test

---

pom.xml

* In order to provide users with the latest supported Hadoop version (which is 2.9.2 atm) we need to add `hadoop-2.9` Maven profile to Spark build so it fits well alongside with `hadoop-2.7` and `hadoop-3.1`
* unit tests from current repo with `-Phadoop-2.9` profile enabled ([spark-build-log-hadoop-2.9-20190408.log](https://github.com/mesosphere/spark/files/3056680/spark-build-log-hadoop-2.9-20190408.log))
* integration tests from [mesosphere/spark-build](https://github.com/mesosphere/spark-build) executed against Spark distribution built with `-Phadoop-2.9` profile enabled

[DCOS-51453][HADOOP] Add Hadoop 2.9 profile

---

docs/configuration.md
resource-managers/mesos/src/main/scala/org/apache/spark/deploy/rest/mesos/MesosRestServer.scala
resource-managers/mesos/src/test/scala/org/apache/spark/deploy/rest/mesos/MesosRestServerSuite.scala

This fix enable the support of `spark.driver.memoryOverhead` property for `mesos`. The default value for the property would be either 10% of the value of `spark.driver.memory` or 384, whichever is maximum.
It also contains unit test.
It resolves [DCOS-34235](https://jira.mesosphere.com/browse/DCOS-34235).
It is a duplicate implementation of [PR#17726](https://github.com/apache/spark/pull/17726) of Apache Spark.
It was tested by running unit test manually.
Added consideration of memory overhead into calculation of driver memory.

[DCOS-34235] spark.mesos.executor.memoryOverhead equivalent for the Driver when running on Mesos

---

resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterSchedulerSource.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerSource.scala

This fix refactors metric names to conform Spark pattern: `<instance>_<source>_metric`:
* dispatcher MetricSource renamed to `dispatcher`
* Mesos Scheduler Backend source renamed to `mesos` so that full metric name looks like e.g. `driver_mesos_resources_cpus_used`
* cleanup of metric names
By manually running Spark jobs submitted via Dispatcher/Metronome/Marathon and a sample Grafana Dashboard in combination with the custom Statsd reporter from https://github.com/mesosphere/spark-build/pull/515:

Improved naming for Mesos metrics and metric sources

---

resource-managers/mesos/src/main/scala/org/apache/spark/deploy/rest/mesos/MesosRestServer.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
resource-managers/mesos/src/test/scala/org/apache/spark/deploy/rest/mesos/MesosSubmitRequestServletSuite.scala

- Fixes NullPointerException that prevents SparkException being properly logged during task scheduling in Mesos.
- Adds label format validation for properties `spark.mesos.network.labels`, `spark.mesos.task.labels`, and `spark.mesos.driver.labels` in dispatcher.
Manual testing

[DCOS-34549] Mesos label NPE fix

---

core/src/main/scala/org/apache/spark/deploy/master/Master.scala
core/src/main/scala/org/apache/spark/deploy/rest/RestSubmissionServer.scala
core/src/main/scala/org/apache/spark/deploy/rest/StandaloneRestServer.scala
core/src/test/scala/org/apache/spark/deploy/rest/StandaloneRestSubmitSuite.scala
resource-managers/mesos/src/main/scala/org/apache/spark/deploy/mesos/MesosClusterDispatcher.scala
resource-managers/mesos/src/main/scala/org/apache/spark/deploy/rest/mesos/MesosRestServer.scala

Resolves [DCOS-52206](https://jira.mesosphere.com/browse/DCOS-52206) and based on [SPARK-20982](https://issues.apache.org/jira/browse/SPARK-20982).
* Includes `SSLOptions` to REST Server to handle the configurations related to SSL. In case of mesos, it uses `mesos` as namespace for parsing the SSL configurations and in case of standalone REST server, it uses `standalone` as namespace.
* Tested by running Unit Test

 [DCOS-52206] Add TLS support for Spark REST submission server and client

---

resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala
resource-managers/mesos/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackendSuite.scala

This PR is migrated from [PR#57](https://github.com/mesosphere/spark/pull/57)
It uses to check the task launching condition by using list of blacklist nodes maintained in scheduler. Now failure task count for each slave is not used for checking the blacklisting of a node, instead it is used for only metrics reporting of number of failed task.
It is tested with unit test written for the feature.

[DCOS-52207][Spark] Make Mesos Agent Blacklisting behavior configurable and more tolerant of failures.

---

resource-managers/mesos/pom.xml
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterSchedulerSource.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerSource.scala
resource-managers/mesos/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterSchedulerSuite.scala

* Added specific handling of node draining task states - supervised drivers should relaunch without backoff
* Bumped Mesos Java dependency from 1.4.0 to 1.9.0 in order to get access to new `TaskStatus.Reason` values related to node draining
* Minor cleanups to fix scalastyle errors
* unit tests from this repo
* additional unit test for testing new behaviour
* Integration tests from [mesosphere/spark-build](https://github.com/mesosphere/spark-build)
* [New Feature] Node draining support: supervised Drivers restarted immediately if a node is being drained

[DCOS-58386] Node draining support for supervised drivers; Mesos Java bump to 1.9.0

---

docs/running-on-mesos.md
resource-managers/mesos/src/main/scala/org/apache/spark/deploy/rest/mesos/MesosRestServer.scala
resource-managers/mesos/src/test/scala/org/apache/spark/deploy/rest/mesos/MesosSubmitRequestServletSuite.scala

This PR adds role propagation and enforcement capabilities to Mesos Dispatcher.
Currently,  there's no mechanism for enforcing quotas for all Spark applications submitted to a single dispatcher. Users can always provide `spark.mesos.role` as a part of their `spark-submit` configuration and override any role specified in `spark.mesos.dispatcher.driverDefault.`. This PR adds new functionality to Dispatcher:
* new `spark.mesos.dispatcher.role.enforce` configuration property triggers a role override verification and rejects submit requests if a user tries to override the default role
* the role of the Dispatcher is propagated to all the drivers by default. If role enforcement is not enabled, users can still override the default role
* unit tests from this repo
* additional unit test for …

[DCOS-58389] Role propagation and enforcement support for Mesos Dispatcher

---

resource-managers/mesos/src/main/scala/org/apache/spark/deploy/mesos/config.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterScheduler.scala
resource-managers/mesos/src/main/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackend.scala
resource-managers/mesos/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosClusterSchedulerSuite.scala
resource-managers/mesos/src/test/scala/org/apache/spark/scheduler/cluster/mesos/MesosCoarseGrainedSchedulerBackendSuite.scala

This PR adds support in Spark drivers for suppressing Mesos resource offers when max number of executors started. Currently the offers are declined with configurable delay (2 minutes by default).
- Suppresses Mesos offers when the executor cap is reached (dynamic allocation enabled)
- Revives Mesos offers when the executor cap is increased (dynamic allocation enabled)
- Suppresses Mesos offers when max core number is utilized.
- Manually in a DC/OS cluster
- Unit tests
Integration tests will be added to mesosphere/spark-build later in a separate PR
Added support for resource offer suppression when run in a Mesos cluster

DCOS-57560: Suppress/revive support for Mesos
